openapi: 3.0.3
info:
    title: Simple Todos API
    description: A simple API to manage todos
    version: 1.0.0

servers:
    - url: https://jsonplaceholder.typicode.com/

paths:
    /todos:
        get:
            summary: Get all todos
            description: webdsl.text.this[0].title
            responses:
                "200":
                    description: A list of todos
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/Todo"
    /todos/20:
        get:
            summary: Get a todo by ID
            description: Retrieve a todo by their unique ID and show it in gauge webdsl.gauge.this.id
            parameters:
                - name: userId
                  in: path
                  required: true
                  schema:
                      type: string
            responses:
                "200":
                    description: A single todo
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Todo"

components:
    schemas:
        Todo:
            type: object
            properties:
                userId:
                    type: number
                    example: 1
                id:
                    type: number
                    example: 1
                title:
                    type: string
                    example: "John Doe"
                completed:
                    type: boolean
                    example: false
