services:
    webdsl:
        build: ./
        ports:
            - "8082:8080"
        env_file:
            - .env
        environment:
            - WORKERS=1
            - ROOT_PATH=/
        restart: always
