broker_info:
    name: "mycoolbroker"
    type: "MQTT"
    topics:
        - "patata"
        - "psomi"
        - "testboy"

broker_connection_parameters:
    host: "localhost"
    port: 1883

websocket:
    host: "0.0.0.0"
    port: 8765
