brokers:
    - name: "redis"
      type: "REDIS"
      topics:
          - "topic1"
      broker_connection_parameters:
          host: "localhost"
          port: 6379
          username: ""
          password: ""

    - name: "mycoolbroker"
      type: "MQTT"
      topics:
          - "topic2"
      broker_connection_parameters:
          host: "localhost"
          port: 1883
          username: ""
          password: ""

websocket:
    host: "0.0.0.0"
    port: 8765
