services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:80"
        depends_on:
            - backend
        restart: always

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8765:8765"
        restart: always
